name: 'dsci532'
channels:
  - conda-forge
dependencies:
  - ipykernel
  - ipyleaflet
  - ipywidgets
  - matplotlib
  - nbformat
  - numpy
  - pandas
  - pip
  - plotly
  - python=3.12
  - scienceplots
  - scikit-learn
  - seaborn
  - pip:
    - shiny
    - shinywidgets
    - altair<6
    - h3
    - pycountry
    - querychat
    - anthropic
    - chatlas
    - python-dotenv
    - pytest
    - pytest-playwright
    - playwright
    - ibis-framework[duckdb]
